/** KML 2.2 generation + Google Earth Web deep-link construction.
 *
 *  Used by the photo-timestamp reverse-lookup feature (Pettit feedback
 *  2026-05-19). The .kml file opens in Google Earth Desktop; the deep-link
 *  opens Google Earth Web at the same coordinates.
 *
 *  KML 2.2 is the OGC standard, well-supported in Google Earth and
 *  countless other GIS tools. We emit a single Placemark with timestamp +
 *  altitude metadata in the description; altitudeMode=relativeToGround
 *  means Google Earth renders the pin at the supplied altitude (~408km
 *  for ISS) above the surface, not at sea level.
 */

export interface LookupResult {
  timestamp_utc: Date;
  lat: number;
  lon: number;
  alt_km: number;
  tle_age_at_lookup_hours: number;
  confidence: 'high' | 'medium' | 'low';
  source: 'paste' | 'exif';
}

/** XML-escape a string for safe inclusion in a KML text node. */
export function xmlEscape(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/** Build a KML 2.2 document for a single LookupResult.
 *
 *  Renders as a single Placemark at the ISS sub-point. Coordinates in
 *  longitude,latitude,altitude(m) order per KML spec. altitudeMode is
 *  relativeToGround so the pin floats at the ISS altitude — useful for
 *  visualizing the look angle in Google Earth.
 */
export function buildKml(result: LookupResult): string {
  const ts = result.timestamp_utc.toISOString();
  const altMeters = result.alt_km * 1000;
  const lat = result.lat.toFixed(6);
  const lon = result.lon.toFixed(6);
  const sourceLabel = result.source === 'exif' ? 'EXIF DateTimeOriginal' : 'pasted timestamp';
  const confidence = result.confidence;
  const desc = [
    `<b>ISS position at ${xmlEscape(ts)}</b>`,
    `Lat / Lon: ${lat}° / ${lon}°`,
    `Altitude: ${result.alt_km.toFixed(1)} km`,
    `Confidence: ${confidence} (TLE age ${result.tle_age_at_lookup_hours.toFixed(1)} h)`,
    `Source: ${sourceLabel}`,
    'Generated by Orbit Photo Director.',
  ].join('<br/>');
  // KML 2.2 namespace per https://developers.google.com/kml/documentation/kmlreference
  return `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>ISS position at ${xmlEscape(ts)}</name>
    <Placemark>
      <name>ISS @ ${xmlEscape(ts)}</name>
      <description><![CDATA[${desc}]]></description>
      <TimeStamp><when>${xmlEscape(ts)}</when></TimeStamp>
      <Point>
        <altitudeMode>relativeToGround</altitudeMode>
        <coordinates>${lon},${lat},${altMeters.toFixed(1)}</coordinates>
      </Point>
    </Placemark>
  </Document>
</kml>
`;
}

/** Build a Google Earth Web deep-link URL for a LookupResult.
 *
 *  Schema: https://earth.google.com/web/@LAT,LON,ALT(m)a,DISTANCE(m)d,Y°y,H°h,T°t,R°r
 *  - 'a' = altitude in metres above ground
 *  - 'd' = camera distance in metres (we use 1000m = 1km for surface detail)
 *  - 'y' = compass orientation (0 = north up)
 *  - 'h' = heading (0)
 *  - 't' = tilt (0 = looking straight down)
 *  - 'r' = roll (0)
 *
 *  Google Earth Web ignores extra suffixed segments. The format is stable
 *  enough that it's been our anchor since 2017+; if it ever breaks the
 *  fallback is to just drop a "?lat=...&lon=..." query string and let
 *  the user navigate manually.
 */
export function googleEarthWebUrl(result: LookupResult): string {
  const lat = result.lat.toFixed(6);
  const lon = result.lon.toFixed(6);
  return `https://earth.google.com/web/@${lat},${lon},0a,1000d,1y,0h,0t,0r`;
}

/** Build a download filename for a KML based on the lookup timestamp.
 *  Format: iss-position-YYYYMMDD-HHMMSS.kml. UTC components. */
export function kmlFilename(result: LookupResult): string {
  const t = result.timestamp_utc;
  const pad = (n: number, w = 2) => String(n).padStart(w, '0');
  const ymd = `${t.getUTCFullYear()}${pad(t.getUTCMonth() + 1)}${pad(t.getUTCDate())}`;
  const hms = `${pad(t.getUTCHours())}${pad(t.getUTCMinutes())}${pad(t.getUTCSeconds())}`;
  return `iss-position-${ymd}-${hms}.kml`;
}

/** Trigger a browser download of a .kml file for a LookupResult.
 *  Uses Blob + anchor click; revokes the object URL after download to
 *  avoid memory leak on repeated lookups. */
export function downloadKml(result: LookupResult): void {
  const kml = buildKml(result);
  const blob = new Blob([kml], { type: 'application/vnd.google-earth.kml+xml' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = kmlFilename(result);
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  // Give the browser a tick to start the download before revoking.
  setTimeout(() => URL.revokeObjectURL(url), 100);
}
